# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.10.12                # https://pyreadiness.org/3.10
  - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
  - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
  - pip:
    - rpaframework==28.0.0        # https://rpaframework.org/releasenotes.html
    - robocorp==1.4.0             # https://pypi.org/project/robocorp
    - robocorp-browser==2.2.1     # https://pypi.org/project/robocorp-browser
    - asttokens==2.4.1
    - attrs==23.2.0
    - backcall==0.2.0
    - bleach==6.1.0
    - certifi==2024.6.2
    - charset-normalizer==3.3.2
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docopt==0.6.2
    - et-xmlfile==1.1.0
    - exceptiongroup==1.2.1
    - executing==2.0.1
    - fastjsonschema==2.20.0
    - h11==0.14.0
    - idna==3.7
    - ipython==8.12.3
    - jedi==0.19.1
    - jsonschema==4.22.0
    - jsonschema-specifications==2023.12.1
    - matplotlib-inline==0.1.7
    - mistune==3.0.2
    - nbclient==0.10.0
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - numpy==2.0.0
    - openpyxl==3.1.4
    - outcome==1.3.0.post0
    - packaging==24.1
    - pandas==2.2.2
    - pandocfilters==1.5.1
    - parso==0.8.4
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - pipreqs==0.5.0
    - platformdirs==4.2.2
    - ptyprocess==0.7.0
    - pure-eval
